// Code generated by ogen, DO NOT EDIT.

package exasdk

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// Answer implements answer operation.
	//
	// Performs a search based on the query and generates either a direct answer or a detailed summary
	// with citations, depending on the query type.
	//
	// POST /answer
	Answer(ctx context.Context, req *AnswerReq) (*AnswerResponseApplicationJSON, error)
	// FindSimilar implements findSimilar operation.
	//
	// Find similar links to the link provided. Optionally get contents.
	//
	// POST /findSimilar
	FindSimilar(ctx context.Context, req *FindSimilarReq) (*FindSimilarResponse, error)
	// GetContents implements getContents operation.
	//
	// Get Contents.
	//
	// POST /contents
	GetContents(ctx context.Context, req *GetContentsReq) (*ContentsResponse, error)
	// Search implements search operation.
	//
	// Perform a search with a Exa prompt-engineered query and retrieve a list of relevant results.
	// Optionally get contents.
	//
	// POST /search
	Search(ctx context.Context, req *SearchReq) (*SearchResponse, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
