// Code generated by ogen, DO NOT EDIT.

package exasdk

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// Answer implements answer operation.
//
// Performs a search based on the query and generates either a direct answer or a detailed summary
// with citations, depending on the query type.
//
// POST /answer
func (UnimplementedHandler) Answer(ctx context.Context, req *AnswerReq) (r *AnswerResponseApplicationJSON, _ error) {
	return r, ht.ErrNotImplemented
}

// FindSimilar implements findSimilar operation.
//
// Find similar links to the link provided. Optionally get contents.
//
// POST /findSimilar
func (UnimplementedHandler) FindSimilar(ctx context.Context, req *FindSimilarReq) (r *FindSimilarResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// GetContents implements getContents operation.
//
// Get Contents.
//
// POST /contents
func (UnimplementedHandler) GetContents(ctx context.Context, req *GetContentsReq) (r *ContentsResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// Search implements search operation.
//
// Perform a search with a Exa prompt-engineered query and retrieve a list of relevant results.
// Optionally get contents.
//
// POST /search
func (UnimplementedHandler) Search(ctx context.Context, req *SearchReq) (r *SearchResponse, _ error) {
	return r, ht.ErrNotImplemented
}
