// Code generated by ogen, DO NOT EDIT.

package exasdk

// setDefaults set default value of fields.
func (s *AnswerReq) setDefaults() {
	{
		val := bool(false)
		s.Stream.SetTo(val)
	}
	{
		val := bool(false)
		s.Text.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ContentsRequest) setDefaults() {
	{
		val := int(10000)
		s.LivecrawlTimeout.SetTo(val)
	}
	{
		val := int(0)
		s.Subpages.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ContentsRequestExtras) setDefaults() {
	{
		val := int(0)
		s.ImageLinks.SetTo(val)
	}
	{
		val := int(0)
		s.Links.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ContentsRequestText1) setDefaults() {
	{
		val := bool(false)
		s.IncludeHtmlTags.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *FindSimilarReq) setDefaults() {
	{
		val := int(10)
		s.NumResults.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *GetContentsReq) setDefaults() {
	{
		val := int(10000)
		s.LivecrawlTimeout.SetTo(val)
	}
	{
		val := int(0)
		s.Subpages.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *GetContentsReqExtras) setDefaults() {
	{
		val := int(0)
		s.ImageLinks.SetTo(val)
	}
	{
		val := int(0)
		s.Links.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *GetContentsReqText1) setDefaults() {
	{
		val := bool(false)
		s.IncludeHtmlTags.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *SearchReq) setDefaults() {
	{
		val := SearchReqType("auto")
		s.Type.SetTo(val)
	}
	{
		val := int(10)
		s.NumResults.SetTo(val)
	}
}
