// Code generated by ogen, DO NOT EDIT.

package exasdk

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleApikey handles apikey security.
	// API key can be provided either via x-api-key header or Authorization header with Bearer scheme.
	HandleApikey(ctx context.Context, operationName OperationName, t Apikey) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

var operationRolesApikey = map[string][]string{
	AnswerOperation:      []string{},
	FindSimilarOperation: []string{},
	GetContentsOperation: []string{},
	SearchOperation:      []string{},
}

func (s *Server) securityApikey(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t Apikey
	const parameterName = "x-api-key"
	value := req.Header.Get(parameterName)
	if value == "" {
		return ctx, false, nil
	}
	t.APIKey = value
	t.Roles = operationRolesApikey[operationName]
	rctx, err := s.sec.HandleApikey(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// Apikey provides apikey security value.
	// API key can be provided either via x-api-key header or Authorization header with Bearer scheme.
	Apikey(ctx context.Context, operationName OperationName) (Apikey, error)
}

func (s *Client) securityApikey(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.Apikey(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"Apikey\"")
	}
	req.Header.Set("x-api-key", t.APIKey)
	return nil
}
