// Code generated by ogen, DO NOT EDIT.

package exasdk

// OperationName is the ogen operation name
type OperationName = string

const (
	AnswerOperation      OperationName = "Answer"
	FindSimilarOperation OperationName = "FindSimilar"
	GetContentsOperation OperationName = "GetContents"
	SearchOperation      OperationName = "Search"
)
